### ISSUE TITLE
empty ephys.10ch

### ISSUE THREAD

**Issue by yooerzf** [nvladimus/ZebrafishFunctionalMaps_LinearRegression#2]
Hi,

I downloaded 2014-08-01fish2_H2B/raw.zip and 2016-07-26fish1_cyto/raw.zip. After I unzipped the raw.zip files. I found both ephys.10ch files are empty. Is this expected?
I am asking this because I meet the error below when I run the .ipynb.

  File "/home/yooerzf/Downloads/FunctionalMaps_2016-07-26fish1_cyto.py", line 75, in <module>
    ephys = behavior.import10ch(rawDir + fName)
  File "/home/yooerzf/SRC/optofish-paper/ZebrafishFunctionalMaps_LinearRegression/lib/behavior.py", line 61, in import10ch
    smoothed_channel1 = np.convolve(ch1, filter_kernel, mode='same')
  File "/home/yooerzf/anaconda3/2019.03/thunder_with_spark/lib/python3.7/site-packages/numpy/core/numeric.py", line 1112, in convolve
    raise ValueError('v cannot be empty')

Thanks,
Zhifeng

**Comment by nvladimus** [comment]
Hi, Zhifeng,
This is odd. I downloaded and unzipped raw.zip files just now, the ephys.10ch files are 908 and 156 MB respectively. Did you download or clone the repo? If you cloned, you need git LFS installed to clone the raw.zip files. It's better to download them directly via browser.

**Comment by yooerzf** [comment]
Hi Nikita,
Many thanks!
The command of downloading was wget -c "https://github.com/optofish-paper/ZebrafishFunctionalMaps_LinearRegression/blob/master/2014-08-01fish2_H2B/raw.zip?raw=true". I use "git lfs clone" this time and everything looks fine.
Best Regards,
Zhifeng
